### ISSUE TITLE
German translation of the menu item

### ISSUE THREAD

**Issue by ygoe** [NumeriusNegidius/Context-Search#24] opened 2017-10-13 20:52 UTC
Instead of

> Search for: abc...

there should be

> Suche nach "abc"

That would be consistent with the existing Google search menu item.

**Comment by NumeriusNegidius** [comment] 2017-10-15 12:54
That's two issues in one. The reason it has a colon and an ellipsis is because it's not possible to remove the latter due to [bug 1370228](https://bugzilla.mozilla.org/show_bug.cgi?id=1370228) in Firefox. I thought it would look weird with 

> Search for "abc..."

I've waited with localization until now because I thought more strings would be added, but I think it probably is time to tackle issue #12 now.

I'll close this issue as a duplicate of #12 and open a new issue regarding the quotes and ellipsis.

**Closed by NumeriusNegidius** 2017-10-15 12:54 UTC

**Comment by NumeriusNegidius** [comment] 2017-10-15 18:18
By the way: localization is now supported in the new version. You are more than welcome to contribute to the German translation! :)
