### ISSUE TITLE
Allow bookmark folder selection other than "Searches"

### ISSUE THREAD

**Issue by swartzja** [NumeriusNegidius/Context-Search#75] opened 2019-12-03 14:22 UTC
Greetings. I have a feature request. I would love an option to pick any folder in my bookmarks instead of requiring the name "Searches". I would imagine that would help people who don't notice the "S" must be capitalized as well. Thanks.

**Comment by NumeriusNegidius** [comment] 2020-02-08 22:57
Dupe of #29

**Closed by NumeriusNegidius** 2020-02-08 22:57 UTC
